### ISSUE TITLE
Typescript Duplicate identifier 'data'

### ISSUE THREAD

**Issue by VascoBotelho** [meister03/discord-hybrid-sharding#15]
**Describe the bug**
typescript error at modules/discord-hybrid-sharding/typings.d.ts:121:16

**Screenshots & Error Stack**
![image](https://user-images.githubusercontent.com/48020247/134802965-69bba863-58d2-4478-87d9-2f901ed81981.png)
![image](https://user-images.githubusercontent.com/48020247/134803169-60ead67e-c352-4e6e-960d-497c0ddae28f.png)

**Discord.js Version**
13.1.0

**Comment by meister03** [comment]
Sorry for late response. I do not check my Inbox so often. You can get fast help in our Discord Server.

Yeah, it was a merge mistake. Lemme fix it and push a new version. Thx for notifying

**Comment by meister03** [comment]
Updated it, could you check it now?

**Comment by VascoBotelho** [comment]
OK, I have tested, and it's not showing the error any more.
Thank you
