### ISSUE TITLE
Expose a way for the IPC system to be used for advanced users and some wrappers around it

### ISSUE THREAD

**Issue by Deivu** [meister03/discord-hybrid-sharding#18]
**Is your feature request related to a problem? Please describe.**
I saw this library from just looking around github, and I do think it can be a good alternative for Kurasuta, but I would like some features, or exposing some internals to be used for advanced users to benefit from. While this request is made for advanced users to profit, there's no real drawback this will introduce for basic users, and will benefit both of the users.

What I ask to be considered or implemented

- A listener in child and master process where you can read **custom** ipc messages that doesn't involve the library internal ipc messages

- A repliable system for this listener I mentioned above, something like **receptive** in veza ipc, where in if I supplied the send() function with an object with receptive is set to true, the master process is expected to return a response, then .send() will resolve with this response, and if receptive is false, it will function as a send and do not wait for response method
Check https://github.com/Deivu/Azuma/blob/c916a3324aaa523a05e85a8fb9462ed96cfd0aa3/src/client/RequestManager.js#L126 (Send)
Check 
https://github.com/Deivu/Azuma/blob/c916a3324aaa523a05e85a8fb9462ed96cfd0aa3/src/ratelimits/AzumaManager.js#L42
(Reply)

**Describe the solution you'd like**
Probably you can implement a structure for this custom ipc, where in you will track messages that is sent with receptive set to true, then track and resolve back the data to the correct cluster / context whom who sent the request. eg a cluster can have multiple .send() with receptive set to true, so ensure the data is sent properly and routed across those

Right now I modify kurasuta on its ipc to get what I wanted working, but due to veza ipc being wonky sometimes (though I didn't have crashing issues on it, but wrong responses do get routed to my clusters sometimes) which is something I don't really like, so I do hope this sharding manager do implement this on the package level so I don't need to do some structure replacement etc etc just to get custom messages and replies across all my clusters

**Comment by meister03** [comment]
Hi,
Interesting request.
The first idea can be easily added, by adding a field `.system: true` on all Internal IPC Messages and then the Messages can be filtered by the individuals themselves by adding `if(message?.system) return;`

The second idea is a little bit more complicated. I would like to share my Ideas on Discord (Sent you a friend request)

**Comment by meister03** [comment]
Has been added on `^1.3.3`. Please open a new Issue on further Feature Requests
