### ISSUE TITLE
TypeError: Manager is not a constructor

### ISSUE THREAD

**Issue by FunkiCraft** [meister03/discord-hybrid-sharding#22]
Get the error:

const crosshost = new Manager(`mongodburl`, {
                                      ^

TypeError: Manager is not a constructor

**Comment by meister03** [comment]
Where did you got this?
Could you provide me the links?
Btw, we switched to a `tcp-server`, `discord-cross-hosting` does not support `mongodb` anymore.

**Comment by meister03** [comment]
Use the latest version and upgrade to it...
