### ISSUE TITLE
Mistyped DJsClient on typings.d.ts file

### ISSUE THREAD

**Issue by VascoBotelho** [meister03/discord-hybrid-sharding#28]
**Describe the bug**
it's not a bug, it's a mistyped word.
Typescript will throw an error.

**Expected behavior**
`DJSClient` to be `DJsClient` or vice versa.

**Discord.js Version**
 - 13.6.0

**Comment by meister03** [comment]
should be fixed in the master branch, could you check it?

**Comment by VascoBotelho** [comment]
The error is still here.

**Comment by meister03** [comment]
@VascoBotelho did you updated to latest?

**Comment by VascoBotelho** [comment]
Mine is on version 1.4.6

**Comment by meister03** [comment]
Cpuld you test out the master branch?

**Comment by VascoBotelho** [comment]
In the master branch, the typing is correct.

**Comment by VascoBotelho** [comment]
On 1.4.6 the type error continues.

**Comment by meister03** [comment]
New version should be out and fixed.
