### ISSUE TITLE
Add more events

### ISSUE THREAD

**Issue by hydrox19** [meister03/discord-hybrid-sharding#4]
**Is your feature request related to a problem? Please describe.**
I wanted to have more data like what's going on with clusters

**Describe the solution you'd like**
Some thing like
```js
<Manager>.on('clusterDisconnect', cluster => {
    <Client>.clusters.get(cluster.id).reconnect(timeout);
});
```
and few more events for clusters

**Describe alternatives you've considered**
Nope

**Additional context**
Nope

**Comment by Drxckzyz** [comment]
There are already events for the clusters, its like discord.js
You dont listen on the Manager for cluster events, you listen for the events in the cluster itself

**Comment by meister03** [comment]
And we added a debug event on the manager
