### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by REMOOO** [meister03/discord-hybrid-sharding#44]
Error in Queue

![Capture](https://user-images.githubusercontent.com/13511097/172446904-50cf1d6d-7299-4ee7-b049-2a495758252b.PNG)

**Comment by meister03** [comment]
Update to Nodev14 or higher

**Comment by TsWin** [comment]
No, I think it's an error of Node v17 and higher.
I know someone that had the same issue with Node v17 and v18, but finally when he went back to v16 everything was ok.
@REMOOO What is your node version?
