### ISSUE TITLE
Reclustering makes all clusters enter maintenance mode

### ISSUE THREAD

**Issue by paring-chan** [meister03/discord-hybrid-sharding#62]
**Describe the bug**
If all of the clusters become maintenance mode, it can't achieve zero-downtime reclustering.

**Expected behavior**
The existing clusters should run until the new clusters become ready.

**Screenshots & Error Stack**
![image](https://user-images.githubusercontent.com/68010770/187954232-9f6fb8f9-6ff6-4752-b9e1-b376e0f4b6d6.png)

**Discord.js Version**

- 14.3.0

**Comment by meister03** [comment]
It does, when you have proper handling
