### ISSUE TITLE
ClusterManager is not a constructor

### ISSUE THREAD

**Issue by superJK92iscool** [meister03/discord-hybrid-sharding#63]
**Describe the bug**
iI get "ClusterManager is not a constructor" when using p2m to run the bot.
(**To Reproduce**)
use form-fox and add support for discord-hybrid-sharding
**Expected behavior**
Bot should work
**Screenshots & Error Stack**
[logs.txt](https://github.com/meister03/discord-hybrid-sharding/files/9590748/logs.txt)

**Discord.js Version**
13.7.0

**Additional context**

**Comment by superJK92iscool** [comment]
Same when running 
```
node bot/Cluster.js
```
 in the main dir

**Comment by meister03** [comment]
which hybrid sharding version are you using?

**Comment by meister03** [comment]
I think you are using the githubs readme, which is the new typescript rewrite

**Comment by superJK92iscool** [comment]
> I think you are using the githubs readme, which is the new typescript rewrite

I got it to work by using the master branch's readme file but when I start the bot I get
```node
error: tuple concurrently updated
1|cluster  |     at Parser.parseErrorMessage (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:287:98)
1|cluster  |     at Parser.handlePacket (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:126:29)
1|cluster  |     at Parser.parse (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:39:38)
1|cluster  |     at Socket.<anonymous> (C:\Users\super\form-fox\node_modules\pg-protocol\dist\index.js:11:42)
1|cluster  |     at Socket.emit (node:events:527:28)
1|cluster  |     at addChunk (node:internal/streams/readable:315:12)
1|cluster  |     at readableAddChunk (node:internal/streams/readable:289:9)
1|cluster  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
1|cluster  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
1|cluster  |   length: 83,
1|cluster  |   severity: 'ERROR',
1|cluster  |   code: 'XX000',
1|cluster  |   detail: undefined,
1|cluster  |   hint: undefined,
1|cluster  |   position: undefined,
1|cluster  |   internalPosition: undefined,
1|cluster  |   internalQuery: undefined,
1|cluster  |   where: undefined,
1|cluster  |   schema: undefined,
1|cluster  |   table: undefined,
1|cluster  |   column: undefined,
1|cluster  |   dataType: undefined,
1|cluster  |   constraint: undefined,
1|cluster  |   file: 'heapam.c',
1|cluster  |   line: '4271',
1|cluster  |   routine: 'simple_heap_update'
1|cluster  | }
1|cluster  | error: tuple concurrently updated
1|cluster  |     at Parser.parseErrorMessage (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:287:98)
1|cluster  |     at Parser.handlePacket (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:126:29)
1|cluster  |     at Parser.parse (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:39:38)
1|cluster  |     at Socket.<anonymous> (C:\Users\super\form-fox\node_modules\pg-protocol\dist\index.js:11:42)
1|cluster  |     at Socket.emit (node:events:527:28)
1|cluster  |     at addChunk (node:internal/streams/readable:315:12)
1|cluster  |     at readableAddChunk (node:internal/streams/readable:289:9)
1|cluster  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
1|cluster  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
1|cluster  |   length: 83,
1|cluster  |   severity: 'ERROR',
1|cluster  |   code: 'XX000',
1|cluster  |   detail: undefined,
1|cluster  |   hint: undefined,
1|cluster  |   position: undefined,
1|cluster  |   internalPosition: undefined,
1|cluster  |   internalQuery: undefined,
1|cluster  |   where: undefined,
1|cluster  |   schema: undefined,
1|cluster  |   table: undefined,
1|cluster  |   column: undefined,
1|cluster  |   dataType: undefined,
1|cluster  |   constraint: undefined,
1|cluster  |   file: 'heapam.c',
1|cluster  |   line: '4271',
1|cluster  |   routine: 'simple_heap_update'
1|cluster  | }
1|cluster  | error: tuple concurrently updated
1|cluster  |     at Parser.parseErrorMessage (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:287:98)
1|cluster  |     at Parser.handlePacket (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:126:29)
1|cluster  |     at Parser.parse (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:39:38)
1|cluster  |     at Socket.<anonymous> (C:\Users\super\form-fox\node_modules\pg-protocol\dist\index.js:11:42)
1|cluster  |     at Socket.emit (node:events:527:28)
1|cluster  |     at addChunk (node:internal/streams/readable:315:12)
1|cluster  |     at readableAddChunk (node:internal/streams/readable:289:9)
1|cluster  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
1|cluster  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
1|cluster  |   length: 83,
1|cluster  |   severity: 'ERROR',
1|cluster  |   code: 'XX000',
1|cluster  |   detail: undefined,
1|cluster  |   hint: undefined,
1|cluster  |   position: undefined,
1|cluster  |   internalPosition: undefined,
1|cluster  |   internalQuery: undefined,
1|cluster  |   where: undefined,
1|cluster  |   schema: undefined,
1|cluster  |   table: undefined,
1|cluster  |   column: undefined,
1|cluster  |   dataType: undefined,
1|cluster  |   constraint: undefined,
1|cluster  |   file: 'heapam.c',
1|cluster  |   line: '4271',
1|cluster  |   routine: 'simple_heap_update'
1|cluster  | }
```

**Comment by superJK92iscool** [comment]
And also, the one thing that is probably unavoidable is nodejs windows in the background (I am on windows)

**Comment by superJK92iscool** [comment]
> > I think you are using the githubs readme, which is the new typescript rewrite
> 
> 
> 
> I got it to work by using the master branch's readme file but when I start the bot I get
> 
> ```node
> 
> error: tuple concurrently updated
> 
> 1|cluster  |     at Parser.parseErrorMessage (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:287:98)
> 
> 1|cluster  |     at Parser.handlePacket (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:126:29)
> 
> 1|cluster  |     at Parser.parse (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:39:38)
> 
> 1|cluster  |     at Socket.<anonymous> (C:\Users\super\form-fox\node_modules\pg-protocol\dist\index.js:11:42)
> 
> 1|cluster  |     at Socket.emit (node:events:527:28)
> 
> 1|cluster  |     at addChunk (node:internal/streams/readable:315:12)
> 
> 1|cluster  |     at readableAddChunk (node:internal/streams/readable:289:9)
> 
> 1|cluster  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
> 
> 1|cluster  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
> 
> 1|cluster  |   length: 83,
> 
> 1|cluster  |   severity: 'ERROR',
> 
> 1|cluster  |   code: 'XX000',
> 
> 1|cluster  |   detail: undefined,
> 
> 1|cluster  |   hint: undefined,
> 
> 1|cluster  |   position: undefined,
> 
> 1|cluster  |   internalPosition: undefined,
> 
> 1|cluster  |   internalQuery: undefined,
> 
> 1|cluster  |   where: undefined,
> 
> 1|cluster  |   schema: undefined,
> 
> 1|cluster  |   table: undefined,
> 
> 1|cluster  |   column: undefined,
> 
> 1|cluster  |   dataType: undefined,
> 
> 1|cluster  |   constraint: undefined,
> 
> 1|cluster  |   file: 'heapam.c',
> 
> 1|cluster  |   line: '4271',
> 
> 1|cluster  |   routine: 'simple_heap_update'
> 
> 1|cluster  | }
> 
> 1|cluster  | error: tuple concurrently updated
> 
> 1|cluster  |     at Parser.parseErrorMessage (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:287:98)
> 
> 1|cluster  |     at Parser.handlePacket (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:126:29)
> 
> 1|cluster  |     at Parser.parse (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:39:38)
> 
> 1|cluster  |     at Socket.<anonymous> (C:\Users\super\form-fox\node_modules\pg-protocol\dist\index.js:11:42)
> 
> 1|cluster  |     at Socket.emit (node:events:527:28)
> 
> 1|cluster  |     at addChunk (node:internal/streams/readable:315:12)
> 
> 1|cluster  |     at readableAddChunk (node:internal/streams/readable:289:9)
> 
> 1|cluster  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
> 
> 1|cluster  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
> 
> 1|cluster  |   length: 83,
> 
> 1|cluster  |   severity: 'ERROR',
> 
> 1|cluster  |   code: 'XX000',
> 
> 1|cluster  |   detail: undefined,
> 
> 1|cluster  |   hint: undefined,
> 
> 1|cluster  |   position: undefined,
> 
> 1|cluster  |   internalPosition: undefined,
> 
> 1|cluster  |   internalQuery: undefined,
> 
> 1|cluster  |   where: undefined,
> 
> 1|cluster  |   schema: undefined,
> 
> 1|cluster  |   table: undefined,
> 
> 1|cluster  |   column: undefined,
> 
> 1|cluster  |   dataType: undefined,
> 
> 1|cluster  |   constraint: undefined,
> 
> 1|cluster  |   file: 'heapam.c',
> 
> 1|cluster  |   line: '4271',
> 
> 1|cluster  |   routine: 'simple_heap_update'
> 
> 1|cluster  | }
> 
> 1|cluster  | error: tuple concurrently updated
> 
> 1|cluster  |     at Parser.parseErrorMessage (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:287:98)
> 
> 1|cluster  |     at Parser.handlePacket (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:126:29)
> 
> 1|cluster  |     at Parser.parse (C:\Users\super\form-fox\node_modules\pg-protocol\dist\parser.js:39:38)
> 
> 1|cluster  |     at Socket.<anonymous> (C:\Users\super\form-fox\node_modules\pg-protocol\dist\index.js:11:42)
> 
> 1|cluster  |     at Socket.emit (node:events:527:28)
> 
> 1|cluster  |     at addChunk (node:internal/streams/readable:315:12)
> 
> 1|cluster  |     at readableAddChunk (node:internal/streams/readable:289:9)
> 
> 1|cluster  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
> 
> 1|cluster  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
> 
> 1|cluster  |   length: 83,
> 
> 1|cluster  |   severity: 'ERROR',
> 
> 1|cluster  |   code: 'XX000',
> 
> 1|cluster  |   detail: undefined,
> 
> 1|cluster  |   hint: undefined,
> 
> 1|cluster  |   position: undefined,
> 
> 1|cluster  |   internalPosition: undefined,
> 
> 1|cluster  |   internalQuery: undefined,
> 
> 1|cluster  |   where: undefined,
> 
> 1|cluster  |   schema: undefined,
> 
> 1|cluster  |   table: undefined,
> 
> 1|cluster  |   column: undefined,
> 
> 1|cluster  |   dataType: undefined,
> 
> 1|cluster  |   constraint: undefined,
> 
> 1|cluster  |   file: 'heapam.c',
> 
> 1|cluster  |   line: '4271',
> 
> 1|cluster  |   routine: 'simple_heap_update'
> 
> 1|cluster  | }
> 
> ```
@meister03 Do you know how to fix this

**Comment by meister03** [comment]
this bc the lib you are using

**Comment by superJK92iscool** [comment]
What lib is it though?

**Comment by superJK92iscool** [comment]
I fixed it by running 
```
npm install tuple
``` 
but now the status doesn't update
[bot.txt](https://github.com/meister03/discord-hybrid-sharding/files/9627717/bot.txt) 
is the bot.js file as a .txt file because github doesn't let you upload .js files

**Comment by superJK92iscool** [comment]
The status part start on line 81

**Comment by superJK92iscool** [comment]
``` js
const manager = new Cluster.Manager(`${__dirname}/bot.js`, {
    totalShards: 8, // or 'auto'
    /// Check below for more options
    shardsPerClusters: 4,
    totalClusters: 4,
    mode: 'process', // you can also choose "worker"
    token: 'OTg1NzEwNDA4MDcxNTI0NDEz.GZjEsL.LufCPWj7xfEXLdyqTvyN6-d5WgBpFe8YUNc38g',
});
```
also I only get 2 nodejs windows and not 4

**Comment by meister03** [comment]
@superJK92iscool  you leaked your token, would regenerate it

**Comment by superJK92iscool** [comment]
I already did

**Comment by meister03** [comment]
When it works without the package you are using, then it is not a issue of Hybrid Sharding

**Comment by superJK92iscool** [comment]
> but now the status doesn't update [bot.txt](https://github.com/meister03/discord-hybrid-sharding/files/9627717/bot.txt) is 
> the bot.js file as a .txt file because github doesn't let you upload .js files

What about this part it stopped working when I a bit after I adjusted the time between status the changing?

**Comment by superJK92iscool** [comment]
```
const Cluster = require('discord-hybrid-sharding');

const manager = new Cluster.Manager(`${__dirname}/bot.js`, {
    totalShards: 8, // or 'auto'
    /// Check below for more options
    shardsPerClusters: 4,
    totalClusters: 4,
    mode: 'process', // you can also choose "worker"
    token: (process.env.TOKEN),
});

manager.on('clusterCreate', cluster => console.log(`Launched Cluster ${cluster.id}`));
manager.spawn({ timeout: -1 });
```
Is the Cluster.js file's code (Fixed it so it won't show the token)

**Comment by superJK92iscool** [comment]
@meister03

**Comment by meister03** [comment]
Could you join the discord server please, can assist you there faster

**Comment by superJK92iscool** [comment]
I am my username is superJK92#0001

**Comment by superJK92iscool** [comment]
@meister03 ^^^

**Comment by anish2dev** [comment]
> @meister03 ^^^

If you are done then close it
