### ISSUE TITLE
Problem with express listening port already in use

### ISSUE THREAD

**Issue by KasaiKonoru** [meister03/discord-hybrid-sharding#73]
How I would create a discord bot with dashboard + sharding.

I started it and after the first shard I got every time the error with the port is already listening.
How I can handle this with this discord-hybrid-sharding

**Comment by Digital39999** [comment]
Because your every shard is trying to host express api, you can either move everything to manager file and use IPC system to manage data trough clients, or check if shard is 0, and start only on it.

**Comment by KasaiKonoru** [comment]
ok thank you so much
