### ISSUE TITLE
Get info is not a function

### ISSUE THREAD

**Issue by NotTrellox** [meister03/discord-hybrid-sharding#85]
**Describe the bug**
When i run it show like this

(**To Reproduce**)

**Expected behavior**
Cluster no 1 launched

**Screenshots & Error Stack**
https://media.discordapp.net/attachments/1130018305961365587/1141727352099983410/Screenshot_20230817_190502.jpg
https://media.discordapp.net/attachments/1130018305961365587/1141727325759754270/Screenshot_20230817_190544.jpg
https://media.discordapp.net/attachments/1130018305961365587/1141727325235445871/Screenshot_20230817_190600.jpg

**Discord.js Version**

-   v14

**Additional context**

**Comment by meister03** [comment]
![image](https://github.com/meister03/discord-hybrid-sharding/assets/69507874/21fd9331-52aa-4c23-8a05-037ab40cac5d)
the importing does not make any sense
which version did you installed?
