### ISSUE TITLE
Deno Support?

### ISSUE THREAD

**Issue by lassejlv** [meister03/discord-hybrid-sharding#88]
Does this library support the Deno runtime?

**Comment by meister03** [comment]
> Does this library support the Deno runtime?

You could test it out, but there will be some internal issues. As the package relies on the node internal api for spawning worker_threads/child_processes

**Comment by lassejlv** [comment]
<img width="625" alt="Screenshot 2023-11-17 at 23 03 04" src="https://github.com/meister03/discord-hybrid-sharding/assets/77295879/ba0a0c28-4374-44d4-8206-43732684cbb7">

Does the `Cluster ${cluster.id} has been started.` mean that the shard has started, beacuse then it means it works!
