### ISSUE TITLE
Multiserver support?

### ISSUE THREAD

**Issue by AlloryDante** [meister03/discord-hybrid-sharding#89]
Hey, idk the future of the project, but I was wondering if you could implement horizontal scaling by having like multiple vps's as slaves?

**Comment by NotDemonix** [comment]
It's already a feature, discord-cross-hosting package!

**Comment by AlloryDante** [comment]
> It's already a feature, discord-cross-hosting package!

Sorry I saw it too late. Its perfect for what I need. Tysm!
