### ISSUE TITLE
Issues with ClusterManager

### ISSUE THREAD

**Issue by Connor200024** [meister03/discord-hybrid-sharding#90]
**Describe the bug**
The issue I am having it when trying to run my bot on discord-hybrid-sharding I am now getting this error "throw new Error('NO CHILD/MASTER EXISTS OR SUPPLIED CLUSTER_MANAGER_MODE IS INCORRECT');" But this was working before? I see we are on a new update V2.1.4 is this a new common issue? :) 

**Screenshots & Error Stack**
https://beta.cordx.lol/users/324646179134636043/zITYLhA0.png

**Discord.js Version**

-   Discord V14.14.1

**Additional context**
Just unsure if anyone else is having this issue, Any help would be greatful.

**Comment by meister03** [comment]
Which file are you starting?

**Comment by Connor200024** [comment]
It's shard.js...

**Comment by Nicat-dcw** [comment]
Hi, i have same error

**Comment by meister03** [comment]
> Hi, i have same error

Which file are you starting?
Be sure to start the cluster.js

If it does not work, please send me the client and cluster.js file please

**Comment by Nicat-dcw** [comment]
I starting shard.ts file and i can share files you with adding you project repo? If you sure i can add you or i can send you client file with discord dm

**Comment by meister03** [comment]
> I starting shard.ts file and i can share files you with adding you project repo? If you sure i can add you or i can send you client file with discord dm

Either join the support server or send it via dm.

**Comment by Nicat-dcw** [comment]
Okay
