### ISSUE TITLE
Zero Downtime Reclustering Cluster count

### ISSUE THREAD

**Issue by dazzypark** [meister03/discord-hybrid-sharding#93]
**Describe the bug**
Zero Downtime Reclustering was performed using the code below, but the number of clusters did not increase or decrease as the number of bot servers increased.
Only after completely shutting down the bot and cluster and running it again did the number of clusters increase.
```js
manager.recluster?.start({ restartMode: "rolling" });
```

**Expected behavior**
When Zero Downtime Reclustering is in operation, as the number of bot servers increases, the number of clusters must also increase.

**Discord.js Version**

-   14.14.1

**Comment by warix8** [comment]
I have the same issue but you can use something like that to solve it

```js
const newShardsCount = /* input */;
// check that the newshard amount is bigger than the old one, else increase it by 20% ceiled.
const realShardCount = newShardsCount > this.manager.totalShards ? newShardsCount : Math.ceil(this.manager.totalShards * 1.2);

const data = await this.manager.recluster.start({
  restartMode: 'gracefulSwitch',
  delay: 7e3,
  timeout: -1,
  shardsPerClusters: this.manager.shardsPerClusters,
  totalShards: realShardCount,
  totalClusters: Math.ceil(realShardCount / this.manager.shardsPerClusters),
  shardList: Array.from(Array(realShardCount).keys()),
});
```

**Comment by dazzypark** [comment]
Thank you very much 😍
