### ISSUE TITLE
Example in README not working

### ISSUE THREAD

**Issue by SiebeBaree** [meister03/discord-hybrid-sharding#95]
**Describe the bug**

```js
client.cluster
    .broadcastEval(c => c.guilds.cache.size)
    .then(results => console.log(`${results.reduce((prev, val) => prev + val, 0)} total guilds`));
```
This example doesn't print out anything. I cannot get the total guilds in version 2.1.9

**Expected behavior**

That "6 total guilds" is printed to the console

**Discord.js Version**

-   discord-hybrid-sharding: 2.1.9
-   discord.js: 14.14.1

I'm also using bun in a turborepo.

My code: https://github.com/SiebeBaree/Coinz/blob/development/apps/bot/src/bot.ts

**Comment by meister03** [comment]
@SiebeBaree Bun can not be considered fully compatible with node yet-

Could you check if it works with node.js?
