### ISSUE TITLE
Start all clusters at the same time

### ISSUE THREAD

**Issue by dazzypark** [meister03/discord-hybrid-sharding#98]
**Is your feature request related to a problem? Please describe.**
Start or restart the bot using `<manager>.spawn` or `<manager>.recluster?.start`.
However, as the number of clusters increases, it takes longer.
I have verified that the clusters are powered on one by one, but I wonder what happens if I power on all the clusters at once.
Have you thought about this problem?
Are there any problems that can occur if I power on the clusters at the same time?

**Describe the solution you'd like**
Start all clusters simultaneously

**Describe alternatives you've considered**
Start clusters simultaneously using something like Promise all

(I used Google Translate, so it might be awkward)

**Comment by NotDemonix** [comment]
You can start them at once by making a custom queue. But it's there for a reason, there's a limit of how many connections you can create in x amount of time without getting ratelimited

**Comment by fb-sean** [comment]
Yop starting the clusters faster dosnt make the shard connection faster xD

**Comment by dazzypark** [comment]
Haha, thanks for letting me know. I didn't know that.
